#
# Your Crowdin credentials
#
# project_id_env: CROWDIN_PROJECT_ID
# api_token_env: CROWDIN_PERSONAL_TOKEN
# base_path_env: "CROWDIN_BASE_PATH"
# base_url_env: "CROWDIN_BASE_URL"

#
# Choose file structure in Crowdin
# e.g. true or false
#
preserve_hierarchy: true

#
# Files configuration
#
files:
  [
    {
      source: "/src/pages/en/**/*.mdx",
      translation: "/src/pages/%two_letters_code%/**/%file_name%.mdx",
      ignore:
        [
          "/src/pages/en/blog-index.mdx",
          "/src/pages/en/pgp.mdx",
          "/src/pages/en/blog/xmr2.mdx",
        ],
    },
    {
      source: "/src/pages/404.mdx",
      translation: "/src/pages/404_%two_letters_code%.mdx",
    },
    {
      source: "/src/assets/data/pages/en/**/*.json",
      translation: "/src/assets/data/pages/%two_letters_code%/**/%file_name%.json",
    },
    {
      source: "/src/assets/data/layout/en/**/*.json",
      translation: "/src/assets/data/layout/%two_letters_code%/**/%file_name%.json",
    },
  ]
