name: "Crowdin"

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set credentials in crowdin.yml
        run: |
          echo "project_id: ${{ secrets.CROWDIN_PROJECT_ID }}" >> crowdin.yml
          echo "api_token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}" >> crowdin.yml

      - name: Crowdin push
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
