name: "Deploy hidden service"

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Rsync
        uses: up9cloud/action-rsync@v1.4
        env:
          USER: github
          HOST: ${{ secrets.HIDDEN_SERVICE_HOST }}
          KEY: ${{ secrets.HIDDEN_SERVICE_SSH_KEY }}
          SOURCE: "./www/"
          TARGET: ${{ secrets.HIDDEN_SERVICE_TARGET_DIR }}
          ARGS: "-z -r -v --delete --include=\".*\""
          POST_SCRIPT: |
            ls -a ${{ secrets.HIDDEN_SERVICE_TARGET_DIR }}
